services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/MahakHamid2/text-leech-bot
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - 24349144: API_ID
        sync: false
      - c2620447969162e43504e9ad1b41f566: API_HASH
        sync: false
      - key: WEBHOOK
        sync: false
      - 8080: PORT
        sync: false  # Default port value, update if needed
